// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWGeEqc8pZBdXCNb3TPmgHRn-DRPpJk0',
    appId: '1:155878821043:android:c4afb74369292fa7ff74c6',
    messagingSenderId: '155878821043',
    projectId: 'todoapp-40f35',
    storageBucket: 'todoapp-40f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiU9bKlmOZ9cVTh4_yG0mbf9EDnPTq9yQ',
    appId: '1:155878821043:ios:7485ba197ce2912dff74c6',
    messagingSenderId: '155878821043',
    projectId: 'todoapp-40f35',
    storageBucket: 'todoapp-40f35.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiU9bKlmOZ9cVTh4_yG0mbf9EDnPTq9yQ',
    appId: '1:155878821043:ios:7485ba197ce2912dff74c6',
    messagingSenderId: '155878821043',
    projectId: 'todoapp-40f35',
    storageBucket: 'todoapp-40f35.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );
}
